"""Discord bot implementation and role assignment worker."""

from __future__ import annotations

import logging
import random
import time
from io import BytesIO
from typing import Any

import aiosqlite
import discord
from colorthief import ColorThief
from discord.ext import commands, tasks
from discord import app_commands
from . import db

from .config import Settings
from .osu_client import OsuClient
from .verification import VerificationInput, compute_digit_value

logger = logging.getLogger(__name__)

SR_EMOJIS: dict[int, str] = {
    1: "⭐", 2: "⭐", 3: "⭐", 4: "⭐", 5: "⭐",
    6: "⭐", 7: "⭐", 8: "⭐", 9: "⭐", 10: "⭐",
}

def get_all_digit_role_ids(role_mapping: dict[str, dict[int, int]]) -> set[int]:
    """Flatten configured digit role IDs across modes."""
    return {role_id for mode_map in role_mapping.values() for role_id in mode_map.values()}

def get_sr_emoji(sr: float) -> str:
    """Map SR to a star emoji bucket."""
    stars = max(1, min(10, int(sr)))
    return SR_EMOJIS.get(stars, "⭐")

def get_math_pattern(circles: int, sliders: int, length: int, bpm: float, keys: int, mode: str) -> str:
    """Infer broad pattern style from map stats."""
    total_notes = circles + sliders
    if total_notes <= 0 or length <= 0:
        return "Unknown"
    if mode == "mania":
        ln_ratio = sliders / total_notes
        if ln_ratio > 0.60: return f"Full LN ({int(ln_ratio * 100)}%)"
        if 0.01 <= ln_ratio <= 0.60: return f"Hybrid / LN-heavy ({int(ln_ratio * 100)}%)"
        nps = total_notes / length
        bps = (bpm / 60) if bpm > 0 else 1
        notes_per_beat = nps / bps
        if keys <= 5:
            if notes_per_beat >= 5.5: return "Dense Chordjack / Handstream"
            if notes_per_beat >= 4.3: return "Jumpstream / Chordjack"
            return "Speed / Stream" if bpm > 200 else "Rice / Tech"
        if notes_per_beat >= 8.0: return "Dense Chordjack / Bracket"
        if notes_per_beat >= 6.0: return "Chordstream"
        return "Speed / Stairs" if bpm > 190 else "Rice / Tech"
    if mode == "osu":
        return "Jumps / Streams" if (circles / total_notes) > 0.6 else "Balanced / Tech"
    if mode == "taiko":
        return "Stamina / Finisher" if bpm > 200 else "Rhythmic"
    return "Standard"

async def get_adaptive_embed_color(osu_client: OsuClient, image_url: str | None) -> discord.Color:
    """Build embed color from map cover image."""
    if not image_url:
        return discord.Color.blue()
    try:
        response = await osu_client._http.get(image_url, timeout=10.0)
        if response.status_code != 200:
            return discord.Color.blue()
        palette = ColorThief(BytesIO(response.content)).get_palette(color_count=4)
        r, g, b = max(palette, key=lambda c: c[0] + c[1] + c[2])
        return discord.Color.from_rgb(r, g, b)
    except Exception:
        return discord.Color.blue()

class RoleBot(commands.Bot):
    """Discord bot with slash commands and assignment worker."""

    def __init__(self, *, settings: Settings, osu_client: OsuClient, role_mapping: dict[str, dict[int, int]]) -> None:
        intents = discord.Intents.default()
        intents.guilds = True
        intents.members = True
        intents.message_content = False
        super().__init__(command_prefix="!", intents=intents)
        self.settings = settings
        self.osu_client = osu_client
        self.role_mapping = role_mapping

    async def setup_hook(self) -> None:
        self.poll_pending_assignments.start()

    async def close(self) -> None:
        self.poll_pending_assignments.cancel()
        await self.osu_client.close()
        await super().close()

    @tasks.loop(seconds=5.0)
    async def poll_pending_assignments(self) -> None:
        """Consume assignment queue generated by web verification app."""
        guild = self.get_guild(self.settings.discord_guild_id)
        if guild is None:
            return
        async with aiosqlite.connect(self.settings.database_path) as db_conn:
            async with db_conn.execute("""
                SELECT id, discord_id, role_id, osu_id, osu_username, mode, digit_value
                FROM pending_role_assignments
                WHERE status='pending'
                ORDER BY id ASC
                LIMIT 20
                """) as cursor:
                rows = await cursor.fetchall()
            for row in rows:
                assignment_id, discord_id, role_id, osu_id, osu_username, mode, digit = row
                try:
                    member = guild.get_member(discord_id) or await guild.fetch_member(discord_id)
                    role = guild.get_role(role_id)
                    if member is None or role is None:
                        raise ValueError("member or role not found")
                    await self._replace_digit_roles(member, role)
                    await db_conn.execute(
                        "UPDATE pending_role_assignments SET status='done', processed_at=? WHERE id=?",
                        (int(time.time()), assignment_id),
                    )
                except Exception as exc:
                    await db_conn.execute(
                        "UPDATE pending_role_assignments SET status='failed', processed_at=?, error_message=? WHERE id=?",
                        (int(time.time()), str(exc), assignment_id),
                    )
            await db_conn.commit()

    async def _replace_digit_roles(self, member: discord.Member, target_role: discord.Role) -> None:
        role_ids = get_all_digit_role_ids(self.role_mapping)
        old_roles = [role for role in member.roles if role.id in role_ids]
        if old_roles:
            await member.remove_roles(*old_roles, reason="Replacing osu verification role")
        await member.add_roles(target_role, reason="osu verification success")

def register_commands(bot: RoleBot) -> None:
    """Register bot commands."""

    @bot.hybrid_command(name="linkcode")
    @app_commands.describe(code="Код верификации с сайта (например: EF97A4)")
    async def linkcode(ctx: commands.Context[Any], code: str) -> None:
        """Привязать Discord к сессии верификации по рандомному коду."""
        code = code.strip().upper()
        
        async with aiosqlite.connect(bot.settings.database_path) as db_conn:
            # Ищем сессию в таблице по рандомному коду
            async with db_conn.execute(
                "SELECT id FROM verification_challenges WHERE link_code = ? AND status != 'done'", 
                (code,)
            ) as cursor:
                row = await cursor.fetchone()

            if row is None:
                await ctx.send(f"❌ Код `{code}` не найден или сессия уже завершена.", ephemeral=True)
                return

            challenge_id = row[0]

            # Привязываем Discord ID текущего пользователя к этой сессии
            await db_conn.execute(
                "UPDATE verification_challenges SET discord_id = ? WHERE id = ?",
                (ctx.author.id, challenge_id)
            )
            await db_conn.commit()

        await ctx.send(
            f"✅ **Код `{code}` успешно принят!**\n"
            "Ваш Discord-аккаунт привязан. Теперь вернитесь на сайт и нажмите «Завершить верификацию».",
            ephemeral=True
        )

    @bot.hybrid_command(name="setprofile")
    async def setprofile(ctx: commands.Context[Any], username: str) -> None:
        """Link osu profile to a Discord user and assign digit role."""
        await ctx.defer()
        user = await bot.osu_client.request(f"users/{username}")
        if not user:
            await ctx.send("Игрок osu! не найден.")
            return
        osu_id = int(user["id"])
        osu_username = str(user["username"])
        mode = str(user.get("playmode", "osu"))
        global_rank = (user.get("statistics") or {}).get("global_rank")
        async with aiosqlite.connect(bot.settings.database_path) as db_conn:
            await db_conn.execute(
                """
                INSERT INTO users (discord_id, osu_username, osu_id)
                VALUES (?, ?, ?)
                ON CONFLICT(discord_id) DO UPDATE SET osu_username=excluded.osu_username, osu_id=excluded.osu_id
                """,
                (ctx.author.id, osu_username, osu_id),
            )
            await db_conn.commit()

        status = ""
        if ctx.guild:
            try:
                digit = compute_digit_value(
                    VerificationInput(osu_id=osu_id, username=osu_username, global_rank=global_rank),
                    bot.settings.verification_mode,
                    digit_modulus=bot.settings.digit_modulus,
                )
                role_id = bot.role_mapping.get(mode, {}).get(digit)
                if role_id:
                    target_role = ctx.guild.get_role(role_id)
                    if target_role:
                        await bot._replace_digit_roles(ctx.author, target_role)
                        status = f"Выдана роль **{target_role.name}**."
                    else:
                        status = "Роль не найдена на сервере."
                else:
                    status = f"Нет роли для значения `{digit}`."
            except Exception as exc:
                status = str(exc)

        await ctx.send(f"Профиль osu! **{osu_username}** привязан. {status}")

    @bot.hybrid_command(name="profile")
    @discord.app_commands.choices(
        mode=[
            discord.app_commands.Choice(name="Standard (osu!)", value="osu"),
            discord.app_commands.Choice(name="Mania", value="mania"),
            discord.app_commands.Choice(name="Taiko", value="taiko"),
            discord.app_commands.Choice(name="Catch (fruits)", value="fruits"),
        ]
    )
    async def profile(ctx: commands.Context[Any], username: str | None = None, mode: str | None = None) -> None:
        """Show user profile stats."""
        await ctx.defer()
        target = username
        if not target:
            async with aiosqlite.connect(bot.settings.database_path) as db_conn:
                async with db_conn.execute("SELECT osu_username FROM users WHERE discord_id=?", (ctx.author.id,)) as cursor:
                    row = await cursor.fetchone()
            if not row:
                await ctx.send("Сначала привяжи профиль через `/setprofile`.")
                return
            target = str(row[0])
        
        base = await bot.osu_client.request(f"users/{target}")
        if not base:
            await ctx.send("Игрок не найден.")
            return
        mode = mode or str(base.get("playmode", "osu"))
        u = await bot.osu_client.request(f"users/{target}/{mode}")
        if not u or "error" in u:
            await ctx.send("Ошибка получения данных.")
            return

        s = u.get("statistics", {})
        desc = (
            f"**Режим:** `{mode.capitalize()}`\n"
            f"**Точность:** {float(s.get('hit_accuracy', 0)):.2f}% • **PP:** {float(s.get('pp', 0)):,.2f}\n"
            f"**Ранг:** #{int(s.get('global_rank', 0)) or 0}\n"
        )
        embed = discord.Embed(description=desc, color=0x3498DB)
        embed.set_author(name=f"Статистика {u['username']}", icon_url=u.get("avatar_url"))
        await ctx.send(embed=embed)

    @bot.command(name="sync")
    async def sync(ctx: commands.Context[Any]) -> None:
        """Sync slash commands (Owner only)."""
        if bot.settings.discord_owner_id and ctx.author.id != bot.settings.discord_owner_id:
            await ctx.send("Доступ запрещен.")
            return
        await bot.tree.sync()
        await ctx.send("✅ Команды синхронизированы.")